# Generated by Django 5.2.13 on 2026-04-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('medicament', 'Médicament'), ('materiel_medical', 'Matériel médical'), ('equipement_lourd', 'Équipement lourd'), ('consommable', 'Consommable médical'), ('diagnostic', 'Diagnostic'), ('mobilier', 'Mobilier médical'), ('laboratoire', 'Laboratoire'), ('protection', 'Protection / Hygiène'), ('implant', 'Implants / Chirurgie'), ('other', 'Autre')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
    ]
